Ahidjo, Chris (Ext) - thanks the libraries are working
 
I need your help to troubleshoot model promotion
 
it returns the following error
 
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:sts::117439318503:assumed-role/RRDBKRDEV_AWS_DBKF1UNITYCATALOGEUDEVAILAB/m=K0e7wYGAR2yZTzTVt4MIrw,s=V5a2ZvsxRzSomCToUiE1mw is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::novartisrs3adevief1ailab001/applications/vdws0006448/data/unity/models/59652426-56bf-48e0-a36b-c5dddf29fbc5/versions/aa91baef-aaa5-4dfd-ac54-af52e7c1b64a/model.pkl" with an explicit deny in a resource-based policy
 
Which is coming from this task 
 
Submitting task PutObjectTask(transfer_id=0, {'bucket': 'novartisrs3adevief1ailab001', 'key': 'applications/vdws0006448/data/unity/models/59652426-56bf-48e0-a36b-c5dddf29fbc5/versions/aa91baef-aaa5-4dfd-ac54-af52e7c1b64a/python_env.yaml', 'extra_args': {}}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f2cb5388f70> for transfer request: 0.
 
where we need to find a way to pass extra_args': {} such as KMS to make it work
 
Ok. Can I go eat quickly and we can do call ?
 
Only tomorrow, please check the branch token_generation_model_promotion once you are back. This code is already deployed in the accounts 56 and 36
 
 
Code for you to reproduce the issue: https://formulaone-eu-west-1-dev-ai-workspace.cloud.databricks.com/editor/notebooks/3960682424021338?o=1522847799419204
Databricks - Sign In
 
