2025-07-02T17:45:23.166Z
[ERROR] RuntimeError: Invalid event, no requestContext provided
Traceback (most recent call last):
  File "/var/task/model_function.py", line 137, in lambda_handler
    result = dispatcher_helper.dispatch_method(dispatch_table, event)
  File "/var/task/utils/dispatcher_helper.py", line 119, in dispatch_method
    authorizer = _get_request_context_authorizer(event)
  File "/var/task/utils/dispatcher_helper.py", line 47, in _get_request_context_authorizer
    raise RuntimeError("Invalid event, no requestContext provided")

[ERROR] RuntimeError: Invalid event, no requestContext provided Traceback (most recent call last):   File "/var/task/model_function.py", line 137, in lambda_handler     result = dispatcher_helper.dispatch_method(dispatch_table, event)   File "/var/task/utils/dispatcher_helper.py", line 119, in dispatch_method     authorizer = _get_request_context_authorizer(event)   File "/var/task/utils/dispatcher_helper.py", line 47, in _get_request_context_authorizer     raise RuntimeError("Invalid event, no requestContext provided")
2025-07-02T17:45:23.168Z
END RequestId: c598de8c-e86f-4c96-b692-8c1401ce765f
2025-07-02T17:45:23.168Z
REPORT RequestId: c598de8c-e86f-4c96-b692-8c1401ce765f Duration: 2.49 ms Billed Duration: 3 ms Memory Size: 1024 MB Max Memory Used: 151 MB
2025-07-02T17:46:37.887Z
START RequestId: c958561a-5fc7-4858-b616-bf5c4fc021ff Version: $LATEST
2025-07-02T17:46:37.887Z
[INFO] 2025-07-02T17:46:37.887Z c958561a-5fc7-4858-b616-bf5c4fc021ff Invokation params: {'action': 'promote_model_registration', 'model_name': 'irisclassifier', 'model_version': '1', 'model_source': 'databricks_registry', 'workspace_id': 'DWS0004069', 'deployment_target': 'dev'}
2025-07-02T17:46:37.887Z
[ERROR] RuntimeError: Invalid event, no requestContext provided Traceback (most recent call last):   File "/var/task/model_function.py", line 137, in lambda_handler     result = dispatcher_helper.dispatch_method(dispatch_table, event)   File "/var/task/utils/dispatcher_helper.py", line 119, in dispatch_method     authorizer = _get_request_context_authorizer(event)   File "/var/task/utils/dispatcher_helper.py", line 47, in _get_request_context_authorizer     raise RuntimeError("Invalid event, no requestContext provided")
2025-07-02T17:46:37.889Z
END RequestId: c958561a-5fc7-4858-b616-bf5c4fc021ff
2025-07-02T17:46:37.889Z
REPORT RequestId: c958561a-5fc7-4858-b616-bf5c4fc021ff Duration: 1.65 ms Billed Duration: 2 ms Memory Size: 1024 MB Max Memory Used: 151 MB
2025-07-02T17:49:23.351Z
START RequestId: 01062185-848a-4bef-8b82-597b50a41f4d Version: $LATEST
2025-07-02T17:49:23.352Z
[INFO] 2025-07-02T17:49:23.352Z 01062185-848a-4bef-8b82-597b50a41f4d Invokation params: {'action': 'promote_model_registration', 'model_name': 'irisclassifier', 'model_version': '1', 'model_source': 'databricks_registry', 'workspace_id': 'DWS0004069', 'deployment_target': 'dev'}
2025-07-02T17:49:23.352Z
[ERROR] RuntimeError: Invalid event, no requestContext provided Traceback (most recent call last):   File "/var/task/model_function.py", line 137, in lambda_handler     result = dispatcher_helper.dispatch_method(dispatch_table, event)   File "/var/task/utils/dispatcher_helper.py", line 119, in dispatch_method     authorizer = _get_request_context_authorizer(event)   File "/var/task/utils/dispatcher_helper.py", line 47, in _get_request_context_authorizer     raise RuntimeError("Invalid event, no requestContext provided")
2025-07-02T17:49:23.356Z
END RequestId: 01062185-848a-4bef-8b82-597b50a41f4d
2025-07-02T17:49:23.356Z
REPORT RequestId: 01062185-848a-4bef-8b82-597b50a41f4d Duration
