Status: Failed
Test Event Name: test

Response:
{
  "errorMessage": "Invalid event, no requestContext provided",
  "errorType": "RuntimeError",
  "requestId": "01062185-848a-4bef-8b82-597b50a41f4d",
  "stackTrace": [
    "  File \"/var/task/model_function.py\", line 137, in lambda_handler\n    result = dispatcher_helper.dispatch_method(dispatch_table, event)\n",
    "  File \"/var/task/utils/dispatcher_helper.py\", line 119, in dispatch_method\n    authorizer = _get_request_context_authorizer(event)\n",
    "  File \"/var/task/utils/dispatcher_helper.py\", line 47, in _get_request_context_authorizer\n    raise RuntimeError(\"Invalid event, no requestContext provided\")\n"
  ]
}

Function Logs:
START RequestId: 01062185-848a-4bef-8b82-597b50a41f4d Version: $LATEST
[INFO]	2025-07-02T17:49:23.352Z	01062185-848a-4bef-8b82-597b50a41f4d	Invokation params: {'action': 'promote_model_registration', 'model_name': 'irisclassifier', 'model_version': '1', 'model_source': 'databricks_registry', 'workspace_id': 'DWS0004069', 'deployment_target': 'dev'}
[ERROR] RuntimeError: Invalid event, no requestContext provided
Traceback (most recent call last):
  File "/var/task/model_function.py", line 137, in lambda_handler
    result = dispatcher_helper.dispatch_method(dispatch_table, event)
  File "/var/task/utils/dispatcher_helper.py", line 119, in dispatch_method
    authorizer = _get_request_context_authorizer(event)
  File "/var/task/utils/dispatcher_helper.py", line 47, in _get_request_context_authorizer
    raise RuntimeError("Invalid event, no requestContext provided")
END RequestId: 01062185-848a-4bef-8b82-597b50a41f4d
REPORT RequestId: 01062185-848a-4bef-8b82-597b50a41f4d	Duration: 3.94 ms	Billed Duration: 4 ms	Memory Size: 1024 MB	Max Memory Used: 151 MB

Request ID: 01062185-848a-4bef-8b82-597b50a41f4d
